const express = require('express')
const router = express.Router()
const index = require('./routes/index')
const login = require('./routes/login')
const stadd = require('./routes/stadd')
const stex = require('./routes/stex')
const adminManager = require('./controller/adminManager')
const stsearch = require('./routes/stsearch')
const check = require('./controller/check')
const approve = require('./controller/approve')
const refuse = require('./controller/refuse')
const logout = require('./controller/logout')
router.use(index, login, stadd, stex, stsearch,adminManager,check,approve,refuse,logout)
module.exports = router
